from lackey.InputEmulation import Mouse
import lackey
from re_tests_plugin import *
import time
import os
import platform


def test_add_database():
    mouse = Mouse()
    direction = Mouse.WHEEL_DOWN
    steps = 9
    mouse.wheel(direction, steps)
    lackey.click("bt_create_new_connection.png")
    time.sleep(2)
    lackey.click("icon_character.png")
    location = lackey.find("icon_character_open.png")
    if location:
        mouse.move(location.getCenter())
    mouse.wheel(direction, steps)
    lackey.click("UTF.png")
    lackey.click("conection_name.png")
    lackey.type("Phone_test")
    lackey.click("data_base_file.png")
    lackey.type("phone_test")
    lackey.click("user_name.png")
    lackey.type("sysdba")
    lackey.click("password.png")
    lackey.type("masterkey")
    lackey.click("bt_create.png")
    result2 = lackey.exists("register_database.png")
    lackey.click("bt_yes.png")
    time.sleep(2)
    result3 = lackey.exists("icon_phone_test_clicked.png")
    assert result2 != None
    assert result3 != None


def test_info_database():
    if lackey.exists("icon_phone_test_clicked.png"):
        lackey.doubleClick("icon_phone_test_clicked.png")
    elif lackey.exists("icon_phone_test.png"):
        lackey.doubleClick("icon_phone_test.png")
    else:
        pass
    lackey.click("tree_plus.png")
    time.sleep(1)
    result1 = lackey.exists("icon_info_phone_test.png")
    lackey.click("icon_info_users1.png")
    time.sleep(1)
    position = lackey.find("tree_plus1.png")

    if position is not None:
        positions = list(lackey.findAll("tree_plus1.png"))
        if len(positions) >= 2:
            positions[1].click()
        else:
            lackey.click("tree_plus.png")
    result2 = lackey.exists("icon_info_users_open.png")
    time.sleep(3)
    lackey.click("icon_connected.png")
    mouse_controller = Mouse()
    distance = 30
    current_position = mouse_controller.getPos()
    new_position = current_position.offset(0, distance)
    mouse_controller.move(new_position)
    time.sleep(2)
    assert result1 != None
    assert result2 != None


def test_add_tables():
    if lackey.exists("icon_phone_test_clicked.png"):
        lackey.click("icon_disconnected.png")
    elif lackey.exists("icon_phone_test.png"):
        lackey.click("icon_phone_test.png")
        lackey.click("icon_disconnected.png")
    else:
        pass
    result2 = lackey.exists("tab_query_editor_text.png")
    create_table_sql1 = """CREATE TABLE PHONE (ID_PHONE INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "NAME" VARCHAR(10), "NUMBER" INTEGER NOT NULL, CONSTRAINT PK_PHONE_1 PRIMARY KEY (ID_PHONE));"""
    lackey.type(create_table_sql1)
    lackey.click("bt_format_sql.png")
    result1 = lackey.exists("create_table1.png")
    lackey.click("icon_execute_query.png")
    result3 = lackey.exists("table_create1.png")
    time.sleep(2)
    lackey.type("a", lackey.Key.CTRL)
    lackey.type(lackey.Key.BACKSPACE)
    create_table_sql2= """CREATE TABLE OPERATOR (ID_OPERATOR INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,ID_PHONE INTEGER NOT NULL,"NAME" VARCHAR(10) NOT NULL,"NUMBER" INTEGER NOT NULL,CONSTRAINT PK_OPERATOR_1 PRIMARY KEY (ID_OPERATOR),CONSTRAINT FK_OPERATOR_1 FOREIGN KEY (ID_PHONE) REFERENCES PHONE (ID_PHONE));"""
    lackey.type(create_table_sql2)
    lackey.click("bt_format_sql.png")
    result4 = lackey.exists("create_table2.png")
    lackey.click("icon_execute_query.png")
    time.sleep(2)
    lackey.type("a", lackey.Key.CTRL)
    lackey.type(lackey.Key.BACKSPACE)
    lackey.click("tree_plus.png")
    time.sleep(2)
    lackey.click("tree_plus.png")
    result5 = lackey.exists("tables_info_phone.png")
    lackey.click("icon_connected.png")
    time.sleep(2)
    assert result1 != None
    assert result2 != None
    assert result3 != None
    assert result4 != None
    assert result5 != None



def test_remove_connected_phone():
    time.sleep(2)
    if lackey.exists("icon_phone_test_clicked.png"):
        lackey.click("bt_remove.png")
        lackey.click("bt_yes.png")
    elif lackey.exists("icon_phone_test.png"):
        lackey.click("bt_remove.png")
        lackey.click("bt_yes.png")
    else:
        pass
    time.sleep(2)
    current_os = platform.system()
    if current_os == "Windows":
        file_path = "C:\\Windows\\System32\\PHONE_TEST"
        os.remove(file_path)
    elif current_os == "Linux":
        linux_file_path = "/var/lib/phone_test"
        os.remove(linux_file_path)




