import lackey
from re_tests_plugin import *
import time
#Тестирование открытие дерева объектов базы данных с инструментом ппррфайлер
def test_domain(open_connection):
    lackey.click("tree_plus.png")
    lackey.click("bt_tools.png")
    lackey.click("bt_profiler.png")
    result1 = lackey.exists("icon_info_profiler.png")
    lackey.click("bt_view_extended.png")
    lackey.click("bt_start.png")
    time.sleep(2)
    lackey.doubleClick("icon_tree_domain.png")
    lackey.type(lackey.Key.ADD)
    lackey.doubleClick("icon_domain_empno.png")
    time.sleep(3)
    result2 = lackey.exists("icon_object_panel.png")
    lackey.click("icon_tab_profiler.png")
    lackey.click("bt_stop.png")
    time.sleep(4)
    lackey.click("icon_session.png")
    lackey.type(lackey.Key.DOWN)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_show.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_info.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.click("bt_discard.png")
    lackey.rightClick("icon_info_profiler.png")
    lackey.click("bt_tab_close_all.png")
    assert result1 != None
    assert result2 != None

def test_table(open_connection):
    lackey.click("tree_plus.png")
    lackey.click("bt_tools.png")
    lackey.click("bt_profiler.png")
    result1 = lackey.exists("icon_info_profiler.png")
    lackey.click("bt_view_extended.png")
    lackey.click("bt_start.png")
    time.sleep(2)
    lackey.doubleClick("icon_table.png")
    lackey.type(lackey.Key.ADD)
    lackey.doubleClick("tree_table_name_EMPLOYEE.png")
    time.sleep(3)
    result2 = lackey.exists("icon_object_panel.png")
    lackey.click("icon_tab_profiler.png")
    lackey.click("bt_stop.png")
    time.sleep(4)
    lackey.click("icon_session.png")
    lackey.type(lackey.Key.DOWN)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_show.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_info.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.click("bt_discard.png")
    lackey.rightClick("icon_info_profiler.png")
    lackey.click("bt_tab_close_all.png")
    assert result1 != None
    assert result2 != None

def test_views(open_connection):
    lackey.click("tree_plus.png")
    lackey.click("bt_tools.png")
    lackey.click("bt_profiler.png")
    result1 = lackey.exists("icon_info_profiler.png")
    lackey.click("bt_view_extended.png")
    lackey.click("bt_start.png")
    time.sleep(2)
    lackey.doubleClick("icon_tree_views.png")
    lackey.type(lackey.Key.ADD)
    lackey.doubleClick("icon_views_phone_list.png")
    time.sleep(3)
    result2 = lackey.exists("icon_object_panel.png")
    lackey.click("icon_tab_profiler.png")
    lackey.click("bt_stop.png")
    time.sleep(4)
    lackey.click("icon_session.png")
    lackey.type(lackey.Key.DOWN)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_show.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_info.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.click("bt_discard.png")
    lackey.rightClick("icon_info_profiler.png")
    lackey.click("bt_tab_close_all.png")
    assert result1 != None
    assert result2 != None

def test_procedure(open_connection):
    lackey.click("tree_plus.png")
    lackey.click("bt_tools.png")
    lackey.click("bt_profiler.png")
    result1 = lackey.exists("icon_info_profiler.png")
    lackey.click("bt_view_extended.png")
    lackey.click("bt_start.png")
    time.sleep(2)
    lackey.doubleClick("icon_tree_procedure.png")
    lackey.type(lackey.Key.ADD)
    lackey.doubleClick("bt_exe_budgept.png")
    time.sleep(3)
    result2 = lackey.exists("icon_object_panel.png")
    lackey.click("icon_tab_profiler.png")
    lackey.click("bt_stop.png")
    time.sleep(4)
    lackey.click("icon_session.png")
    lackey.type(lackey.Key.DOWN)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_show.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_info.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.click("bt_discard.png")
    lackey.rightClick("icon_info_profiler.png")
    lackey.click("bt_tab_close_all.png")
    assert result1 != None
    assert result2 != None

def test_triggers(open_connection):
    lackey.click("tree_plus.png")
    lackey.click("bt_tools.png")
    lackey.click("bt_profiler.png")
    result1 = lackey.exists("icon_info_profiler.png")
    lackey.click("bt_view_extended.png")
    lackey.click("bt_start.png")
    time.sleep(2)
    lackey.doubleClick("triggers_table.png")
    lackey.type(lackey.Key.ADD)
    lackey.doubleClick("trigger_emp_no.png")
    time.sleep(3)
    result2 = lackey.exists("icon_object_panel.png")
    lackey.click("icon_tab_profiler.png")
    lackey.click("bt_stop.png")
    time.sleep(4)
    lackey.click("icon_session.png")
    lackey.type(lackey.Key.DOWN)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_show.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_info.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.click("bt_discard.png")
    lackey.rightClick("icon_info_profiler.png")
    lackey.click("bt_tab_close_all.png")
    assert result1 != None
    assert result2 != None

def test_sequences(open_connection):
    lackey.click("tree_plus.png")
    lackey.click("bt_tools.png")
    lackey.click("bt_profiler.png")
    result1 = lackey.exists("icon_info_profiler.png")
    lackey.click("bt_view_extended.png")
    lackey.click("bt_start.png")
    time.sleep(2)
    lackey.doubleClick("icon_tree_sequences.png")
    lackey.type(lackey.Key.ADD)
    lackey.doubleClick("emp_no_sequences.png")
    time.sleep(3)
    result2 = lackey.exists("icon_object_panel.png")
    lackey.click("icon_tab_profiler.png")
    lackey.click("bt_stop.png")
    time.sleep(4)
    lackey.click("icon_session.png")
    lackey.type(lackey.Key.DOWN)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_show.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_info.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.click("bt_discard.png")
    lackey.rightClick("icon_info_profiler.png")
    lackey.click("bt_tab_close_all.png")
    assert result1 != None
    assert result2 != None

def test_users(open_connection):
    lackey.click("tree_plus.png")
    lackey.click("bt_tools.png")
    lackey.click("bt_profiler.png")
    result1 = lackey.exists("icon_info_profiler.png")
    lackey.click("bt_view_extended.png")
    lackey.click("bt_start.png")
    time.sleep(2)
    lackey.doubleClick("icon_tree_users.png")
    lackey.type(lackey.Key.ADD)
    lackey.doubleClick("users_sysdba.png")
    time.sleep(3)
    result2 = lackey.exists("icon_object_panel.png")
    lackey.click("icon_tab_profiler.png")
    lackey.click("bt_stop.png")
    time.sleep(4)
    lackey.click("icon_session.png")
    lackey.type(lackey.Key.DOWN)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_show.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_info.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.click("bt_discard.png")
    lackey.rightClick("icon_info_profiler.png")
    lackey.click("bt_tab_close_all.png")
    assert result1 != None
    assert result2 != None


def test_indices(open_connection):
    lackey.click("tree_plus.png")
    lackey.click("bt_tools.png")
    lackey.click("bt_profiler.png")
    result1 = lackey.exists("icon_info_profiler.png")
    lackey.click("bt_view_extended.png")
    lackey.click("bt_start.png")
    time.sleep(2)
    lackey.doubleClick("icon_indices.png")
    lackey.type(lackey.Key.ADD)
    lackey.doubleClick("indices_budgetx.png")
    time.sleep(3)
    lackey.click("bt_OK.png")
    result2 = lackey.exists("icon_object_panel.png")
    lackey.click("icon_tab_profiler.png")
    lackey.click("bt_stop.png")
    time.sleep(4)
    lackey.click("icon_session.png")
    lackey.type(lackey.Key.DOWN)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_show.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.rightClick("sql_scripts_profiler.png")
    lackey.click("bt_info.png")
    time.sleep(3)
    lackey.type(lackey.Key.ESC)
    lackey.click("bt_discard.png")
    lackey.rightClick("icon_info_profiler.png")
    lackey.click("bt_tab_close_all.png")
    assert result1 != None
    assert result2 != None